insert into subject (name, description, grade) values ('Raiders of Atlantis, The', 'Action|Mystery|Sci-Fi', 2);
insert into subject (name, description, grade) values ('Serving Life', 'Documentary', 3);
insert into subject (name, description, grade) values ('Thirst for Love, The (Ai no kawaki)', 'Drama', 1);
insert into subject (name, description, grade) values ('A Most Violent Year', 'Action|Crime|Drama|Thriller', 4);
insert into subject (name, description, grade) values ('Dive! (Dive!: Living off America''s Waste)', 'Documentary', 2);
insert into subject (name, description, grade) values ('Tuxedo, The', 'Action|Comedy', 2);
insert into subject (name, description, grade) values ('The Uninvited Guest', 'Drama|Horror|Mystery|Thriller', 1);
insert into subject (name, description, grade) values ('Stones in Exile', 'Documentary|Musical', 1);
insert into subject (name, description, grade) values ('14 Hours (Fourteen Hours)', 'Drama|Film-Noir|Thriller', 2);
insert into subject (name, description, grade) values ('Blackout', 'Mystery|Thriller', 1);
insert into subject (name, description, grade) values ('Shoes of the Fisherman, The', 'Drama', 3);
insert into subject (name, description, grade) values ('Return to Never Land', 'Adventure|Animation|Children', 1);
insert into subject (name, description, grade) values ('Acapulco, First Beach... To the Left', 'Comedy', 3);
insert into subject (name, description, grade) values ('Summer Storm (Sommersturm)', 'Drama|Romance', 1);
insert into subject (name, description, grade) values ('City Streets', 'Crime|Film-Noir', 4);
insert into subject (name, description, grade) values ('Cheap Detective, The', 'Comedy', 1);
insert into subject (name, description, grade) values ('Calling Bulldog Drummond', 'Crime|Mystery', 1);
insert into subject (name, description, grade) values ('Son of the White Mare', 'Adventure|Animation|Fantasy', 3);
insert into subject (name, description, grade) values ('Sh! The Octopus', 'Comedy|Mystery', 4);
insert into subject (name, description, grade) values ('Brake', 'Crime|Thriller', 1);
insert into subject (name, description, grade) values ('Rolling Thunder', 'Action|Drama', 1);
insert into subject (name, description, grade) values ('Lured', 'Crime|Film-Noir|Mystery|Thriller', 4);
insert into subject (name, description, grade) values ('Luminarias', 'Comedy|Romance', 3);
insert into subject (name, description, grade) values ('Highball', 'Comedy|Drama', 3);
insert into subject (name, description, grade) values ('Manos: The Hands of Fate', 'Horror', 3);
insert into subject (name, description, grade) values ('Forever Hardcore: The Documentary', 'Documentary', 2);
insert into subject (name, description, grade) values ('Dolls and Angels', 'Drama', 2);
insert into subject (name, description, grade) values ('Collision: Christopher Hitchens vs. Douglas Wilson', 'Documentary', 1);
insert into subject (name, description, grade) values ('Organizer, The (I compagni)', 'Crime|Drama', 4);
insert into subject (name, description, grade) values ('North and South, Book II', 'Drama|Romance|War', 4);
insert into subject (name, description, grade) values ('A Story of Children and Film', 'Documentary', 1);
insert into subject (name, description, grade) values ('Star Wars: Episode I - The Phantom Menace', 'Action|Adventure|Sci-Fi', 2);
insert into subject (name, description, grade) values ('Colourful (Karafuru)', 'Animation|Drama|Fantasy|Mystery', 3);
insert into subject (name, description, grade) values ('Despicable Me 2', 'Animation|Children|Comedy|IMAX', 4);
insert into subject (name, description, grade) values ('Silent Night, Deadly Night III: Better Watch Out!', 'Horror', 4);
insert into subject (name, description, grade) values ('Dona Flor and Her Two Husbands (Dona Flor e Seus Dois Maridos)', 'Comedy', 4);
insert into subject (name, description, grade) values ('Flight of Fury', 'Action', 2);
insert into subject (name, description, grade) values ('Night in Old Mexico, A', 'Drama|Western', 2);
insert into subject (name, description, grade) values ('Ellie Parker', 'Comedy|Drama', 2);
insert into subject (name, description, grade) values ('Widow of St. Pierre, The (Veuve de Saint-Pierre, La)', 'Drama|Romance', 2);
insert into subject (name, description, grade) values ('Killing Floor, The', 'Crime|Horror|Mystery', 4);
insert into subject (name, description, grade) values ('Wing Commander', 'Action|Sci-Fi', 4);
insert into subject (name, description, grade) values ('Third Star', 'Comedy|Drama', 2);
insert into subject (name, description, grade) values ('Gemini (Sôseiji)', 'Drama|Fantasy|Horror|Mystery|Thriller', 1);
insert into subject (name, description, grade) values ('Stranger Than Paradise', 'Comedy|Drama', 1);
insert into subject (name, description, grade) values ('Lady Eve, The', 'Comedy|Romance', 3);
insert into subject (name, description, grade) values ('The Key', 'Drama', 1);
insert into subject (name, description, grade) values ('Fantastic Planet, The (Planète sauvage, La)', 'Animation|Sci-Fi', 1);
insert into subject (name, description, grade) values ('No Flesh Shall Be Spared', 'Documentary', 1);
insert into subject (name, description, grade) values ('Double Team', 'Action', 4);
insert into subject (name, description, grade) values ('Very Natural Thing, A', 'Drama', 4);
insert into subject (name, description, grade) values ('Candidate, The', 'Drama', 3);
insert into subject (name, description, grade) values ('Future by Design', 'Documentary|Sci-Fi', 2);
insert into subject (name, description, grade) values ('Emperor''s Naked Army Marches On, The (Yuki Yukite shingun)', 'Documentary', 4);
insert into subject (name, description, grade) values ('Tere Naam', 'Romance', 4);
insert into subject (name, description, grade) values ('Horse in the Gray Flannel Suit, The', 'Children|Comedy', 2);
insert into subject (name, description, grade) values ('Sorrow and the Pity, The (Le chagrin et la pitié)', 'Documentary|War', 3);
insert into subject (name, description, grade) values ('Summer Storm (Sommersturm)', 'Drama|Romance', 1);
insert into subject (name, description, grade) values ('Don''t Tell Mom the Babysitter''s Dead', 'Comedy', 4);
insert into subject (name, description, grade) values ('Imagine I''m Beautiful', 'Drama', 1);
insert into subject (name, description, grade) values ('Bloodbath at the House of Death', 'Comedy|Horror', 3);
insert into subject (name, description, grade) values ('Reds', 'Drama|Romance', 2);
insert into subject (name, description, grade) values ('Scorpion King 2: Rise of a Warrior, The', 'Action|Adventure|Fantasy', 4);
insert into subject (name, description, grade) values ('Harry in Your Pocket', 'Comedy|Crime|Drama', 4);
insert into subject (name, description, grade) values ('Mutiny on the Bounty', 'Adventure|Drama', 1);
insert into subject (name, description, grade) values ('At Sword''s Point', 'Adventure', 1);
insert into subject (name, description, grade) values ('The Gambler', 'Crime|Drama|Thriller', 1);
insert into subject (name, description, grade) values ('That Darn Cat!', 'Children|Comedy|Mystery', 4);
insert into subject (name, description, grade) values ('Grbavica: The Land of My Dreams (Grbavica)', 'Drama', 4);
insert into subject (name, description, grade) values ('The Left Handed Gun', 'Crime|Drama|Western', 1);
insert into subject (name, description, grade) values ('Tusk', 'Comedy|Drama|Horror', 4);
insert into subject (name, description, grade) values ('World According to Dick Cheney, The ', 'Documentary', 1);
insert into subject (name, description, grade) values ('Forgotten', 'Drama|Mystery|Thriller', 3);
insert into subject (name, description, grade) values ('Swamp Water', 'Drama', 1);
insert into subject (name, description, grade) values ('Dog Day Afternoon', 'Crime|Drama', 2);
insert into subject (name, description, grade) values ('Surf Nazis Must Die', 'Action|Comedy|Drama|Horror', 4);
insert into subject (name, description, grade) values ('Magnificent Obsession', 'Drama|Romance', 2);
insert into subject (name, description, grade) values ('Boy Meets Girl', 'Comedy', 3);
insert into subject (name, description, grade) values ('Married to It', 'Comedy|Drama', 2);
insert into subject (name, description, grade) values ('Latin Music USA', 'Documentary|Musical', 1);
insert into subject (name, description, grade) values ('LOL (Laughing Out Loud)', 'Comedy', 3);
insert into subject (name, description, grade) values ('Outside Man, The (Un homme est mort)', 'Action|Crime|Drama|Thriller', 1);
insert into subject (name, description, grade) values ('Straight Shooting', 'Western', 3);
insert into subject (name, description, grade) values ('Slaughter of the Innocents', 'Crime|Horror|Mystery|Thriller', 4);
insert into subject (name, description, grade) values ('American Gun', 'Drama', 2);
insert into subject (name, description, grade) values ('Bat People, The', 'Comedy|Drama|Horror|Sci-Fi', 4);
insert into subject (name, description, grade) values ('Bride of the Wind', 'Drama|Musical|Romance', 4);
insert into subject (name, description, grade) values ('In a Dark Place', 'Horror|Mystery|Thriller', 2);
insert into subject (name, description, grade) values ('Foster Brothers, The (Süt kardesler)', 'Comedy', 2);
insert into subject (name, description, grade) values ('Advertising and the End of the World', 'Documentary', 2);
insert into subject (name, description, grade) values ('Warm December, A', 'Drama|Romance', 4);
insert into subject (name, description, grade) values ('Art', 'Drama', 1);
insert into subject (name, description, grade) values ('Seven Invisible Men (Septyni nematomi zmones)', 'Drama', 4);
insert into subject (name, description, grade) values ('Midnight Clear', 'Drama', 4);
insert into subject (name, description, grade) values ('The Universe of Keith Haring', 'Documentary', 1);
insert into subject (name, description, grade) values ('Queens Logic', 'Comedy|Drama', 2);
insert into subject (name, description, grade) values ('Torch Song Trilogy', 'Comedy|Drama|Romance', 3);
insert into subject (name, description, grade) values ('Out to Sea', 'Comedy', 2);
insert into subject (name, description, grade) values ('Popatopolis', 'Documentary', 1);
insert into subject (name, description, grade) values ('Agent Cody Banks 2: Destination London', 'Action|Adventure|Children|Comedy', 2);
insert into subject (name, description, grade) values ('Lake Placid', 'Horror|Thriller', 2);
insert into subject (name, description, grade) values ('Breed, The', 'Horror|Thriller', 4);
insert into subject (name, description, grade) values ('Mother Dao, the Turtlelike (Moeder Dao, de schildpadgelijkende)', 'Documentary', 4);
insert into subject (name, description, grade) values ('Math', 'Comedy', 1);
insert into subject (name, description, grade) values ('Mighty Morphin Power Rangers: The Movie', 'Action|Children', 3);
insert into subject (name, description, grade) values ('In Your Hands (Forbrydelser)', 'Drama', 2);
insert into subject (name, description, grade) values ('Marc Pease Experience, The', 'Comedy|Drama|Musical', 2);
insert into subject (name, description, grade) values ('Blood and Bones (Chi to hone)', 'Drama', 2);
insert into subject (name, description, grade) values ('Signal, The (Señal, La)', 'Drama|Film-Noir|Mystery|Romance', 2);
insert into subject (name, description, grade) values ('12:01 PM', 'Sci-Fi', 1);
insert into subject (name, description, grade) values ('Borrowers, The', 'Adventure|Children|Comedy|Fantasy', 2);
insert into subject (name, description, grade) values ('Babies (Bébé(s))', 'Documentary', 1);
insert into subject (name, description, grade) values ('Forgive Me', 'Comedy', 2);
insert into subject (name, description, grade) values ('Revolver', 'Crime|Drama|Thriller', 1);
insert into subject (name, description, grade) values ('Noah''s Arc Principle, The (Arche Noah Prinzip, Das)', 'Sci-Fi', 2);
insert into subject (name, description, grade) values ('Signos del zodiaco, Los', 'Drama', 2);
insert into subject (name, description, grade) values ('Raising Helen', 'Comedy|Drama|Romance', 2);
insert into subject (name, description, grade) values ('Crows Zero II (Kurôzu Zero II)', 'Action', 2);
insert into subject (name, description, grade) values ('X-Men Origins: Wolverine', 'Action|Sci-Fi|Thriller', 3);
insert into subject (name, description, grade) values ('Frankenweenie', 'Animation|Comedy|Horror|IMAX', 4);
insert into subject (name, description, grade) values ('Calculator', 'Sci-Fi', 4);
insert into subject (name, description, grade) values ('Lush Life', 'Drama|Musical', 4);
insert into subject (name, description, grade) values ('Space Milkshake', 'Comedy|Sci-Fi', 1);
insert into subject (name, description, grade) values ('Grandmaster, The (Yi dai zong shi)', 'Action|Drama|IMAX', 1);
insert into subject (name, description, grade) values ('Love and Lemons (Små citroner gula)', 'Romance', 2);
insert into subject (name, description, grade) values ('Garfield''s Halloween Adventure', 'Animation|Children', 3);
insert into subject (name, description, grade) values ('Dead Air', 'Horror|Sci-Fi|Thriller', 2);
insert into subject (name, description, grade) values ('Seance on a Wet Afternoon', 'Crime|Drama|Thriller', 4);
insert into subject (name, description, grade) values ('Invitation, The (Zaproszenie)', 'Drama', 4);
insert into subject (name, description, grade) values ('Dead Meat', 'Horror', 3);
insert into subject (name, description, grade) values ('Angel Face', 'Crime|Drama|Film-Noir', 2);
insert into subject (name, description, grade) values ('Tales of Ordinary Madness (Storie di Ordinaria Follia)', 'Drama', 4);
insert into subject (name, description, grade) values ('What to Do in Case of Fire (Was tun, wenn''s brennt?)', 'Comedy|Drama', 3);
insert into subject (name, description, grade) values ('Torrente, el brazo tonto de la ley', 'Comedy|Crime', 2);
insert into subject (name, description, grade) values ('Touch of Pink', 'Comedy|Drama|Romance', 2);
insert into subject (name, description, grade) values ('Big Trouble', 'Comedy|Crime', 2);
insert into subject (name, description, grade) values ('Castle of Purity (El castillo de la pureza)', 'Drama', 3);
insert into subject (name, description, grade) values ('Private Romeo', 'Drama', 1);
insert into subject (name, description, grade) values ('Blind Date', 'Comedy|Romance', 3);
insert into subject (name, description, grade) values ('Sabata', 'Action|Western', 1);
insert into subject (name, description, grade) values ('Dark Journey', 'Adventure|Romance|Thriller', 4);
insert into subject (name, description, grade) values ('Sands of Iwo Jima', 'Action|Drama|Romance|War', 3);
insert into subject (name, description, grade) values ('Tropical Malady (Sud pralad)', 'Drama|Fantasy|Romance', 2);
insert into subject (name, description, grade) values ('Plenty', 'Drama', 3);
insert into subject (name, description, grade) values ('When Brendan Met Trudy', 'Comedy|Romance', 4);
insert into subject (name, description, grade) values ('Rape Me (Baise-moi)', 'Crime|Drama|Thriller', 1);
insert into subject (name, description, grade) values ('Silent Wedding (Nunta Muta)', 'Comedy|Drama', 2);
insert into subject (name, description, grade) values ('Mr. 3000', 'Comedy|Drama', 3);
insert into subject (name, description, grade) values ('Dark Water (Honogurai mizu no soko kara)', 'Drama|Horror|Mystery|Thriller', 4);
insert into subject (name, description, grade) values ('4 Months, 3 Weeks and 2 Days (4 luni, 3 saptamâni si 2 zile)', 'Drama', 3);
insert into subject (name, description, grade) values ('Death of a Salesman', 'Drama', 2);
insert into subject (name, description, grade) values ('Kids', 'Drama', 1);
insert into subject (name, description, grade) values ('Inheritance, The (Karami-ai)', 'Drama', 4);
insert into subject (name, description, grade) values ('Playing with Love (Puppy Love) (Maladolescenza)', 'Drama', 2);
insert into subject (name, description, grade) values ('Nobody Lives Forever', 'Crime|Drama|Film-Noir', 2);
insert into subject (name, description, grade) values ('Trapped in the Closet: Chapters 23-33', 'Comedy|Crime|Drama|Musical', 4);
insert into subject (name, description, grade) values ('Bill Maher... But I''m Not Wrong', 'Comedy', 4);
insert into subject (name, description, grade) values ('De nieuwe Wildernis', 'Documentary', 4);
insert into subject (name, description, grade) values ('X-Files: I Want to Believe, The', 'Drama|Mystery|Sci-Fi|Thriller', 4);
insert into subject (name, description, grade) values ('Shun Li and the Poet', 'Drama', 3);
insert into subject (name, description, grade) values ('Queen to Play (Joueuse)', 'Drama', 4);
insert into subject (name, description, grade) values ('SIS', 'Action|Crime|Drama|Thriller', 2);
insert into subject (name, description, grade) values ('Titicut Follies', 'Documentary|Drama', 4);
insert into subject (name, description, grade) values ('Alice in the Cities (Alice in den Stadten)', 'Drama', 1);
insert into subject (name, description, grade) values ('Tyrannosaur', 'Drama', 1);
insert into subject (name, description, grade) values ('Flowers in the Attic', 'Drama|Thriller', 4);
insert into subject (name, description, grade) values ('Summertime', 'Comedy', 3);
insert into subject (name, description, grade) values ('Start the Revolution Without Me', 'Comedy', 1);
insert into subject (name, description, grade) values ('SOS - en segelsällskapsresa', 'Comedy', 4);
insert into subject (name, description, grade) values ('Missionary Man', 'Action|Drama|Thriller|Western', 1);
insert into subject (name, description, grade) values ('American Me', 'Drama', 3);
insert into subject (name, description, grade) values ('Master, The (Huang Fei Hong jiu er zhi long xing tian xia)', 'Action', 1);
insert into subject (name, description, grade) values ('The First Movie', 'Documentary', 1);
insert into subject (name, description, grade) values ('Nutcracker, The', 'Children|Fantasy|Musical', 4);
insert into subject (name, description, grade) values ('Honeymooners, The', 'Comedy', 3);
insert into subject (name, description, grade) values ('Blue Smoke', 'Drama|Romance|Thriller', 4);
insert into subject (name, description, grade) values ('Calvary', 'Comedy|Drama', 4);
insert into subject (name, description, grade) values ('Girl Who Kicked the Hornet''s Nest, The (Luftslottet som sprängdes)', 'Action|Crime|Mystery', 2);
insert into subject (name, description, grade) values ('Speed Zone! (a.k.a. Cannonball Run III)', 'Action|Comedy', 2);
insert into subject (name, description, grade) values ('Bravo Two Zero ', 'Adventure|Thriller|War', 1);
insert into subject (name, description, grade) values ('Salsa', 'Musical|Romance', 3);
insert into subject (name, description, grade) values ('Dylan Dog: Dead of Night', 'Comedy|Horror|Mystery|Thriller', 4);
insert into subject (name, description, grade) values ('Out of Time', 'Crime|Drama|Thriller', 4);
insert into subject (name, description, grade) values ('Happy-Go-Lucky', 'Comedy|Drama', 3);
insert into subject (name, description, grade) values ('Idiocracy', 'Adventure|Comedy|Sci-Fi|Thriller', 1);
insert into subject (name, description, grade) values ('Invisible Man Returns, The', 'Horror|Sci-Fi', 3);
insert into subject (name, description, grade) values ('Silent Night, Bloody Night', 'Horror', 1);
insert into subject (name, description, grade) values ('Blow-Up (Blowup)', 'Drama|Mystery', 1);
insert into subject (name, description, grade) values ('Mrs. Winterbourne', 'Comedy|Romance', 2);
insert into subject (name, description, grade) values ('Paul Williams Still Alive', 'Comedy|Documentary|Musical', 3);
insert into subject (name, description, grade) values ('Dr. Who and the Daleks', 'Adventure|Children|Sci-Fi', 4);
insert into subject (name, description, grade) values ('More About the Children of Noisy Village (a.k.a. More About the Children of Bullerby Village) (Mer om oss barn i Bullerbyn)', 'Children', 1);
insert into subject (name, description, grade) values ('911 in Plane Site', 'Documentary', 3);
insert into subject (name, description, grade) values ('Close My Eyes', 'Drama|Romance', 1);
insert into subject (name, description, grade) values ('Jesse Stone: Benefit of the Doubt', 'Crime|Drama', 4);
insert into subject (name, description, grade) values ('Backfire', 'Crime|Film-Noir|Mystery|Romance|Thriller', 2);
insert into subject (name, description, grade) values ('Little City', 'Comedy|Romance', 2);
insert into subject (name, description, grade) values ('Waking Up in Reno', 'Comedy|Romance', 3);
insert into subject (name, description, grade) values ('Mr. Bug Goes to Town (a.k.a. Hoppity Goes to Town)', 'Animation|Children|Comedy|Fantasy|Musical', 4);
insert into subject (name, description, grade) values ('Who Are the DeBolts? [And Where Did They Get 19 Kids?]', 'Documentary', 4);
insert into subject (name, description, grade) values ('Jim Jefferies: Alcoholocaust', 'Comedy', 4);
insert into subject (name, description, grade) values ('Lunopolis', 'Sci-Fi', 1);
insert into subject (name, description, grade) values ('Scent of a Woman', 'Drama', 1);
insert into subject (name, description, grade) values ('Rooster''s Breakfast (Petelinji zajtrk)', 'Drama', 3);
insert into subject (name, description, grade) values ('Captain from Castile', 'Adventure|Drama', 1);
insert into subject (name, description, grade) values ('The Year Without a Santa Claus', 'Animation|Children', 4);
insert into subject (name, description, grade) values ('Free Willy 3: The Rescue', 'Adventure|Children|Drama', 2);
insert into subject (name, description, grade) values ('Loaded', 'Action|Crime|Drama|Thriller', 1);
insert into subject (name, description, grade) values ('Hansel & Gretel', 'Drama|Fantasy|Horror|Mystery|Thriller', 2);
insert into subject (name, description, grade) values ('Red Hook Summer', 'Drama', 3);
insert into subject (name, description, grade) values ('Midnight Clear', 'Drama', 3);
insert into subject (name, description, grade) values ('Message from Akira Kurosawa: For Beautiful Movies, A (Kurosawa Akira kara no messêji: Utsukushii eiga o)', 'Documentary', 4);
insert into subject (name, description, grade) values ('Love You You', 'Romance', 3);
insert into subject (name, description, grade) values ('A Christmas Kiss', 'Romance', 2);
insert into subject (name, description, grade) values ('Raanjhanaa', 'Drama|Romance', 3);
insert into subject (name, description, grade) values ('Hell Up in Harlem', 'Crime', 4);
insert into subject (name, description, grade) values ('Little Birds', 'Drama', 1);
insert into subject (name, description, grade) values ('Searching for Sugar Man', 'Documentary', 3);
insert into subject (name, description, grade) values ('Liberty Heights', 'Drama', 3);
insert into subject (name, description, grade) values ('Men in Black (a.k.a. MIB)', 'Action|Comedy|Sci-Fi', 3);
insert into subject (name, description, grade) values ('Yes Men Fix the World, The', 'Documentary', 3);
insert into subject (name, description, grade) values ('Pitch Perfect', 'Comedy|Musical', 4);
insert into subject (name, description, grade) values ('Return of Dracula, The', 'Horror', 1);
insert into subject (name, description, grade) values ('Death Wish 5: The Face of Death', 'Action|Drama', 1);
insert into subject (name, description, grade) values ('Christmas Carol, A', 'Children|Drama|Fantasy', 4);
insert into subject (name, description, grade) values ('Godzilla Raids Again (Gojira no gyakushû)', 'Action|Drama|Horror|Romance|Sci-Fi', 4);
insert into subject (name, description, grade) values ('''Hellboy'': The Seeds of Creation', 'Action|Adventure|Comedy|Documentary|Fantasy', 4);
insert into subject (name, description, grade) values ('Young in Heart, The', 'Comedy|Drama', 1);
insert into subject (name, description, grade) values ('Den enskilde medborgaren', 'Comedy', 1);
insert into subject (name, description, grade) values ('Une étudiante d''aujourd''hui', 'Documentary', 2);
insert into subject (name, description, grade) values ('Toys in the Attic', 'Drama', 3);
insert into subject (name, description, grade) values ('Street with No Name, The', 'Crime|Drama|Film-Noir|Thriller', 2);
insert into subject (name, description, grade) values ('Quare Fellow, The (a.k.a. The Condemned Man)', 'Drama', 2);
insert into subject (name, description, grade) values ('Welcome to Sarajevo', 'Drama|War', 2);
insert into subject (name, description, grade) values ('Wedding Weekend, The (Sing Now or Forever Hold Your Peace) (Shut Up and Sing)', 'Comedy|Drama', 4);
insert into subject (name, description, grade) values ('Vidal Sassoon: The Movie', 'Documentary', 4);
insert into subject (name, description, grade) values ('In Order Not to Be Here', '(no genres listed)', 2);
insert into subject (name, description, grade) values ('Codebreaker', 'Documentary|Drama', 3);
insert into subject (name, description, grade) values ('Knock Off', 'Action', 1);
insert into subject (name, description, grade) values ('Ouch (Aïe)', 'Comedy', 1);
insert into subject (name, description, grade) values ('Entre Amigos (Planta 4ª)', 'Comedy|Drama', 2);
insert into subject (name, description, grade) values ('San Quentin', 'Drama', 2);
insert into subject (name, description, grade) values ('School Ties', 'Drama', 4);
insert into subject (name, description, grade) values ('FernGully 2: The Magical Rescue', 'Adventure|Animation|Children|Fantasy', 4);
insert into subject (name, description, grade) values ('Son of Batman', 'Action|Adventure|Animation|Crime|Fantasy', 1);
insert into subject (name, description, grade) values ('Sadie Thompson', 'Drama', 2);
insert into subject (name, description, grade) values ('On a Clear Day', 'Drama', 1);
insert into subject (name, description, grade) values ('Richard Pryor Live on the Sunset Strip', 'Comedy|Documentary', 1);
insert into subject (name, description, grade) values ('Final Conflict, The (a.k.a. Omen III: The Final Conflict)', 'Horror|Thriller', 3);
insert into subject (name, description, grade) values ('Girl on the Bridge, The (Fille sur le pont, La)', 'Drama|Romance', 1);
insert into subject (name, description, grade) values ('God told Me To', 'Crime|Horror|Mystery|Sci-Fi|Thriller', 2);
insert into subject (name, description, grade) values ('Red Lights (Feux rouges)', 'Drama', 4);
insert into subject (name, description, grade) values ('Invisible Woman, The', 'Comedy|Romance|Sci-Fi', 3);
insert into subject (name, description, grade) values ('Shakthi: The Power', 'Action|Drama', 4);
insert into subject (name, description, grade) values ('Sarafina!', 'Drama', 3);
insert into subject (name, description, grade) values ('Better Tomorrow III: Love and Death in Saigon, A', 'Action|Thriller|War', 3);
insert into subject (name, description, grade) values ('Galileo', 'Drama', 2);
insert into subject (name, description, grade) values ('Fort Apache', 'Western', 2);
insert into subject (name, description, grade) values ('Psycho III', 'Horror|Thriller', 3);
insert into subject (name, description, grade) values ('Get on Up', 'Drama|Musical', 1);
insert into subject (name, description, grade) values ('Ant Bully, The', 'Adventure|Animation|Children|Comedy|Fantasy|IMAX', 4);
insert into subject (name, description, grade) values ('Seasoning House, The', 'Horror|Thriller', 2);
insert into subject (name, description, grade) values ('Loners (Samotári)', 'Drama', 3);
insert into subject (name, description, grade) values ('Remorques (Stormy Waters)', 'Action|Drama|Romance', 4);
insert into subject (name, description, grade) values ('House Bunny, The', 'Comedy', 2);
insert into subject (name, description, grade) values ('Burnt by the Sun 2 (Utomlyonnye solntsem 2)', 'Drama', 3);
insert into subject (name, description, grade) values ('Ballad of the Little Soldier (Ballade vom kleinen Soldaten)', 'Documentary', 4);
insert into subject (name, description, grade) values ('Idiots and Angels', 'Animation|Drama|Fantasy', 3);
insert into subject (name, description, grade) values ('Chamber of Death (Chambre des morts, La)', 'Crime|Mystery|Thriller', 3);
insert into subject (name, description, grade) values ('Sex & the Other Man', 'Comedy|Drama', 4);
insert into subject (name, description, grade) values ('Best Man, The', 'Comedy|Drama', 1);
insert into subject (name, description, grade) values ('Breakdown', 'Action|Thriller', 2);
insert into subject (name, description, grade) values ('Little Bit of Soul, A', 'Comedy', 1);
insert into subject (name, description, grade) values ('Encore', 'Comedy|Drama', 3);
insert into subject (name, description, grade) values ('Nocturna', 'Adventure|Animation|Children|Fantasy|Mystery', 4);
insert into subject (name, description, grade) values ('Candidate, The', 'Drama', 2);
insert into subject (name, description, grade) values ('Aspen', 'Documentary', 3);
insert into subject (name, description, grade) values ('Directed by John Ford', 'Documentary', 3);
insert into subject (name, description, grade) values ('Camouflage', 'Action|Comedy', 4);
insert into subject (name, description, grade) values ('Stash House', 'Thriller', 2);
insert into subject (name, description, grade) values ('13 Ghosts', 'Horror', 2);
insert into subject (name, description, grade) values ('One Crazy Summer', 'Comedy', 3);
insert into subject (name, description, grade) values ('Name of the Rose, The (Name der Rose, Der)', 'Crime|Drama|Mystery|Thriller', 1);
insert into subject (name, description, grade) values ('Human Tornado, The', 'Action|Comedy', 3);
insert into subject (name, description, grade) values ('This Is the End', 'Action|Comedy', 1);
insert into subject (name, description, grade) values ('Naked Jungle, The', 'Adventure|Drama', 3);
insert into subject (name, description, grade) values ('Mosquito Net, The (La mosquitera)', 'Drama', 1);
insert into subject (name, description, grade) values ('Lethal Weapon 2', 'Action|Comedy|Crime|Drama', 1);
insert into subject (name, description, grade) values ('Hand of Peace: Pope Pius XII and the Holocaust, A', 'Documentary', 4);
insert into subject (name, description, grade) values ('Deep Blue Sea, The', 'Drama|Romance', 3);
insert into subject (name, description, grade) values ('Bottled Up', 'Comedy|Drama', 3);
insert into subject (name, description, grade) values ('Trilogy of Terror', 'Horror|Thriller', 2);
insert into subject (name, description, grade) values ('Amores Perros (Love''s a Bitch)', 'Drama|Thriller', 1);
insert into subject (name, description, grade) values ('Cabinet of Dr. Ramirez, The', 'Comedy', 2);
insert into subject (name, description, grade) values ('Now and Forever', 'Drama|Romance', 3);
insert into subject (name, description, grade) values ('Other Dream Team, The', 'Documentary', 2);
insert into subject (name, description, grade) values ('DarkWolf', 'Horror', 1);
insert into subject (name, description, grade) values ('Grumpy Old Men', 'Comedy', 4);
insert into subject (name, description, grade) values ('Colder Kind of Death, A', 'Crime|Drama|Mystery', 1);
insert into subject (name, description, grade) values ('Call of the Wild, The', 'Action|Adventure|Drama|Romance|Western', 3);
insert into subject (name, description, grade) values ('Lady Vanishes, The', 'Action|Comedy|Mystery|Romance', 3);
insert into subject (name, description, grade) values ('Morituri', 'Drama|War', 4);
insert into subject (name, description, grade) values ('Loving', 'Comedy|Drama', 1);
insert into subject (name, description, grade) values ('Walk in the Sun, A', 'War', 4);
insert into subject (name, description, grade) values ('Bread, My Sweet, The (a.k.a. Wedding for Bella, A)', 'Drama|Romance', 2);
insert into subject (name, description, grade) values ('Speed Zone! (a.k.a. Cannonball Run III)', 'Action|Comedy', 4);
insert into subject (name, description, grade) values ('King of Texas', 'Drama|Western', 2);
insert into subject (name, description, grade) values ('Wilson', 'Drama', 4);
insert into subject (name, description, grade) values ('Camille Claudel 1915', 'Drama', 4);
insert into subject (name, description, grade) values ('Manual of Love 2 (Manuale d''amore (capitoli successivi))', 'Comedy|Romance', 4);
insert into subject (name, description, grade) values ('Chosen One, The', 'Comedy|Drama', 2);
insert into subject (name, description, grade) values ('Just Go with It', 'Comedy|Romance', 4);
insert into subject (name, description, grade) values ('Apollo 13', 'Adventure|Drama|IMAX', 2);
insert into subject (name, description, grade) values ('Shadow People', 'Drama', 3);
insert into subject (name, description, grade) values ('Zatoichi in Desperation (Shin Zatôichi monogatari: Oreta tsue) (Zatôichi 24)', 'Action|Adventure|Drama', 2);
insert into subject (name, description, grade) values ('Lay the Favorite', 'Comedy', 4);
insert into subject (name, description, grade) values ('The War at Home', 'Documentary|War', 4);
insert into subject (name, description, grade) values ('Taking Off', 'Comedy|Drama', 4);
insert into subject (name, description, grade) values ('Bang Bang Club, The', 'Drama', 4);
insert into subject (name, description, grade) values ('ReGeneration', 'Documentary', 1);
insert into subject (name, description, grade) values ('House of Games', 'Crime|Film-Noir|Mystery|Thriller', 4);
insert into subject (name, description, grade) values ('Eight Below', 'Action|Adventure|Drama|Romance', 4);
insert into subject (name, description, grade) values ('Organization, The', 'Crime|Drama|Thriller', 1);
insert into subject (name, description, grade) values ('Police Academy 6: City Under Siege', 'Comedy|Crime', 3);
insert into subject (name, description, grade) values ('Zero Tolerance (Noll tolerans)', 'Action|Crime|Thriller', 1);
insert into subject (name, description, grade) values ('Jonathan Livingston Seagull', 'Drama', 3);
insert into subject (name, description, grade) values ('Little Soldier (Lille soldat)', 'Drama', 1);
insert into subject (name, description, grade) values ('Most Wanted', 'Action|Thriller', 3);
insert into subject (name, description, grade) values ('We Live Again', 'Drama', 4);
insert into subject (name, description, grade) values ('Walker, The', 'Drama|Mystery', 2);
insert into subject (name, description, grade) values ('Final Inquiry, The (Inquiry, The) (inchiesta, L'')', 'Adventure|Drama|Mystery', 2);
insert into subject (name, description, grade) values ('Bad Luck Love', 'Crime|Drama', 1);
insert into subject (name, description, grade) values ('The Land Before Time VI: The Secret of Saurus Rock', 'Animation|Children', 2);
insert into subject (name, description, grade) values ('Out Cold', 'Comedy|Thriller', 1);
insert into subject (name, description, grade) values ('Dead Man Walking', 'Crime|Drama', 4);
insert into subject (name, description, grade) values ('Sherlock Holmes', 'Mystery|Sci-Fi', 3);
insert into subject (name, description, grade) values ('Pit and the Pendulum, The', 'Horror', 3);
insert into subject (name, description, grade) values ('Ringu 2 (Ring 2)', 'Horror|Mystery', 4);
insert into subject (name, description, grade) values ('Dossier 51 (Dossier 51, Le)', 'Crime|Drama', 1);
insert into subject (name, description, grade) values ('Telling Lies in America', 'Drama', 3);
insert into subject (name, description, grade) values ('Toy Story of Terror', 'Animation|Children|Comedy', 1);
insert into subject (name, description, grade) values ('I Accuse', 'Crime|Drama|Thriller', 4);
insert into subject (name, description, grade) values ('Happy Ever Afters', 'Comedy', 1);
insert into subject (name, description, grade) values ('Equinox', 'Adventure|Horror|Mystery', 3);
insert into subject (name, description, grade) values ('Fort Apache, the Bronx', 'Action|Drama', 1);
insert into subject (name, description, grade) values ('Secret Things (Choses secrètes)', 'Drama', 1);
insert into subject (name, description, grade) values ('Benji', 'Adventure|Children', 1);
insert into subject (name, description, grade) values ('Tommy Boy', 'Comedy', 1);
insert into subject (name, description, grade) values ('King and I, The', 'Animation|Children', 3);
insert into subject (name, description, grade) values ('Wolverine, The', 'Action|Adventure|Fantasy|Sci-Fi', 1);
insert into subject (name, description, grade) values ('Dracula (Dracula 3D)', 'Horror|Romance|Thriller', 3);
insert into subject (name, description, grade) values ('Hangman''s House', 'Drama', 3);
insert into subject (name, description, grade) values ('Fellini''s Roma (Roma)', 'Drama', 2);
insert into subject (name, description, grade) values ('Dish & the Spoon, The', 'Comedy|Drama|Romance', 1);
insert into subject (name, description, grade) values ('Hannie Caulder', 'Comedy|Crime|Drama|Western', 4);
insert into subject (name, description, grade) values ('American Pimp', 'Documentary', 4);
insert into subject (name, description, grade) values ('Big Girls Don''t Cry (Große Mädchen weinen nicht)', 'Drama|Romance', 4);
insert into subject (name, description, grade) values ('Back Stage', 'Documentary', 4);
insert into subject (name, description, grade) values ('Debt, The (Dlug)', 'Crime|Drama|Thriller', 4);
insert into subject (name, description, grade) values ('Top Dog', 'Action|Comedy|Crime|Thriller', 1);
insert into subject (name, description, grade) values ('Asylum', 'Horror', 1);
insert into subject (name, description, grade) values ('Heart of Dragon (Long de xin)', 'Action|Comedy|Crime|Drama|War', 1);
insert into subject (name, description, grade) values ('Quartet', 'Drama|Romance', 4);
insert into subject (name, description, grade) values ('Buddy Holly Story, The', 'Drama', 1);
insert into subject (name, description, grade) values ('Brice Man, The (Brice de Nice)', 'Comedy', 3);
insert into subject (name, description, grade) values ('Midnight in the Garden of Good and Evil', 'Crime|Drama|Mystery', 3);
insert into subject (name, description, grade) values ('Long Walk Home, The', 'Drama', 1);
insert into subject (name, description, grade) values ('Coney Island', 'Comedy', 4);
insert into subject (name, description, grade) values ('Judgement Day', '(no genres listed)', 4);
insert into subject (name, description, grade) values ('Caged', 'Crime|Drama', 2);
insert into subject (name, description, grade) values ('If Lucy Fell', 'Comedy|Romance', 1);
insert into subject (name, description, grade) values ('Once Upon a Time in Phuket (En gång i Phuket)', 'Comedy', 2);
insert into subject (name, description, grade) values ('Seven Years in Tibet', 'Adventure|Drama|War', 2);
insert into subject (name, description, grade) values ('Sheitan', 'Comedy|Horror|Thriller', 2);
insert into subject (name, description, grade) values ('No One Dies in Lily Dale', 'Documentary', 4);
insert into subject (name, description, grade) values ('Cup, The (Phörpa)', 'Comedy', 1);
insert into subject (name, description, grade) values ('The Forgotten Woman', 'Documentary', 4);
insert into subject (name, description, grade) values ('Poolboy: Drowning Out the Fury', 'Comedy', 4);
insert into subject (name, description, grade) values ('Side Street', 'Crime|Drama|Film-Noir', 1);
insert into subject (name, description, grade) values ('2 Guns', 'Action|Comedy|Crime', 3);
insert into subject (name, description, grade) values ('Lucia', 'Drama|Romance|Sci-Fi|Thriller', 4);
insert into subject (name, description, grade) values ('King''s Game (Kongekabale)', 'Thriller', 3);
insert into subject (name, description, grade) values ('Thirst (Bakjwi)', 'Drama|Horror', 3);
insert into subject (name, description, grade) values ('Yellow Submarine', 'Adventure|Animation|Comedy|Fantasy|Musical', 4);
insert into subject (name, description, grade) values ('Colonel Redl (Oberst Redl)', 'Drama', 3);
insert into subject (name, description, grade) values ('Jeffrey', 'Comedy|Drama', 4);
insert into subject (name, description, grade) values ('Blood of the Vampire', 'Horror|Sci-Fi', 4);
insert into subject (name, description, grade) values ('Topkapi', 'Adventure|Comedy|Thriller', 1);
insert into subject (name, description, grade) values ('Man Exposed', 'Comedy|Drama', 3);
insert into subject (name, description, grade) values ('Ironclad 2: Battle for Blood', 'Action|Adventure', 4);
insert into subject (name, description, grade) values ('End of Suburbia: Oil Depletion and the Collapse of the American Dream', 'Documentary', 3);
insert into subject (name, description, grade) values ('Ploy', 'Drama', 2);
insert into subject (name, description, grade) values ('Laurence Anyways', 'Drama|Romance', 3);
insert into subject (name, description, grade) values ('Oliver Twist', 'Crime|Drama', 3);
insert into subject (name, description, grade) values ('Two Bits', 'Drama', 2);
insert into subject (name, description, grade) values ('Night Out, A', 'Comedy', 2);
insert into subject (name, description, grade) values ('To Rome with Love', 'Comedy', 3);
insert into subject (name, description, grade) values ('Whatever Works', 'Comedy|Romance', 1);
insert into subject (name, description, grade) values ('You''re Missing the Point', 'Comedy', 4);
insert into subject (name, description, grade) values ('Gaucho, The', 'Adventure|Romance', 1);
insert into subject (name, description, grade) values ('Plumm Summer, A', 'Adventure', 2);
insert into subject (name, description, grade) values ('Caótica Ana', 'Comedy|Drama|Mystery|Romance', 2);
insert into subject (name, description, grade) values ('Run for Cover', 'Western', 3);
insert into subject (name, description, grade) values ('Queen of the Mountains', 'Action|Drama', 4);
insert into subject (name, description, grade) values ('Cursed', 'Horror|Thriller', 4);
insert into subject (name, description, grade) values ('Bottled Up', 'Comedy|Drama', 1);
insert into subject (name, description, grade) values ('Adult Camp', 'Comedy', 2);
insert into subject (name, description, grade) values ('Mephisto', 'Drama|War', 2);
insert into subject (name, description, grade) values ('Panama Hattie', 'Comedy|Musical', 2);
insert into subject (name, description, grade) values ('You Kill Me', 'Comedy|Crime|Thriller', 4);
insert into subject (name, description, grade) values ('Nightmare in Las Cruces, A', 'Documentary', 3);
insert into subject (name, description, grade) values ('Divorce Iranian Style', 'Documentary', 3);
insert into subject (name, description, grade) values ('Page Miss Glory', 'Comedy', 1);
insert into subject (name, description, grade) values ('Dirties, The', 'Drama', 1);
insert into subject (name, description, grade) values ('Like Minds (Murderous Intent)', 'Crime|Mystery|Thriller', 3);
insert into subject (name, description, grade) values ('Raid', 'Action|Crime|Drama|Thriller', 1);
insert into subject (name, description, grade) values ('Night of the Living Dead 3D', 'Adventure|Comedy|Fantasy|Horror', 1);
insert into subject (name, description, grade) values ('Boyfriends and Girlfriends (a.k.a. My Girlfriend''s Boyfriend) (L''ami de mon amie)', 'Comedy', 3);
insert into subject (name, description, grade) values ('World on a Wire (Welt am Draht)', 'Crime|Sci-Fi', 4);
insert into subject (name, description, grade) values ('Color of Pomegranates, The (Sayat Nova)', 'Drama', 4);
insert into subject (name, description, grade) values ('Singles', 'Comedy|Drama|Romance', 2);
insert into subject (name, description, grade) values ('Twilight Saga: Breaking Dawn - Part 1, The', 'Adventure|Drama|Fantasy|Romance', 1);
insert into subject (name, description, grade) values ('Fruitvale Station', 'Drama', 3);
insert into subject (name, description, grade) values ('Legend of Lylah Clare, The', 'Drama', 2);
insert into subject (name, description, grade) values ('Ricky & Barabba', 'Comedy', 4);
insert into subject (name, description, grade) values ('Eden of the East the Movie II: Paradise Lost (Higashi no Eden Gekijôban II: Paradise Lost)', 'Animation|Crime|Mystery|Sci-Fi|Thriller', 2);
insert into subject (name, description, grade) values ('Year Ago in Winter, A (Im Winter ein Jahr)', 'Drama', 1);
insert into subject (name, description, grade) values ('The Incident', 'Crime|Drama', 1);
insert into subject (name, description, grade) values ('Somewhat Gentle Man, A (En ganske snill mann)', 'Comedy|Crime|Drama', 2);
insert into subject (name, description, grade) values ('LEGO DC Comics Super Heroes: Justice League vs. Bizarro League', 'Action|Adventure|Animation|Children', 4);
insert into subject (name, description, grade) values ('Tetsuo, the Ironman (Tetsuo)', 'Action|Horror|Sci-Fi|Thriller', 3);
insert into subject (name, description, grade) values ('Prom Queen: The Marc Hall Story', 'Comedy|Drama', 2);
insert into subject (name, description, grade) values ('Interview', 'Drama', 4);
insert into subject (name, description, grade) values ('Dolemite', 'Action|Comedy|Crime|Mystery|Thriller', 2);
insert into subject (name, description, grade) values ('Something Real and Good', 'Drama', 4);
insert into subject (name, description, grade) values ('King, The', 'Drama', 4);
insert into subject (name, description, grade) values ('Gayniggers From Outer Space', 'Comedy|Sci-Fi', 1);
insert into subject (name, description, grade) values ('Lakeview Terrace', 'Drama|Thriller', 1);
insert into subject (name, description, grade) values ('Aragami', 'Action|Fantasy|Horror', 1);
insert into subject (name, description, grade) values ('Lisa', 'Drama|Thriller', 4);
insert into subject (name, description, grade) values ('Mermaid, The (Rusalka)', 'Comedy|Drama|Fantasy', 4);
insert into subject (name, description, grade) values ('Wild Beasts (Wild beasts - Belve feroci)', 'Horror', 3);
insert into subject (name, description, grade) values ('Flypaper', 'Comedy|Crime', 1);
insert into subject (name, description, grade) values ('Serbian Film, A (Srpski film)', 'Horror|Thriller', 4);
insert into subject (name, description, grade) values ('Persuasion', 'Drama|Romance', 2);
insert into subject (name, description, grade) values ('Eaux d''artifice', 'Fantasy', 3);
insert into subject (name, description, grade) values ('Wattstax', 'Documentary|Musical', 3);
insert into subject (name, description, grade) values ('Once Upon a Forest', 'Adventure|Animation|Children|Fantasy', 4);
insert into subject (name, description, grade) values ('In Between Days', 'Drama', 4);
insert into subject (name, description, grade) values ('Pink Panther 2, The', 'Adventure|Comedy|Mystery', 4);
insert into subject (name, description, grade) values ('Barcelona', 'Comedy|Romance', 2);
insert into subject (name, description, grade) values ('Boys, Les', 'Comedy', 1);
insert into subject (name, description, grade) values ('Calamari Union', 'Comedy', 1);
insert into subject (name, description, grade) values ('7 Days in Havana', 'Drama', 2);
insert into subject (name, description, grade) values ('Moog', 'Documentary|Musical', 3);
insert into subject (name, description, grade) values ('Miss Sweden (Fröken Sverige)', 'Drama', 1);
insert into subject (name, description, grade) values ('The Gilded Cage', 'Comedy', 2);
insert into subject (name, description, grade) values ('Power (Jew Süss)', 'Drama|Romance', 1);
insert into subject (name, description, grade) values ('Captain Abu Raed', 'Drama', 2);
insert into subject (name, description, grade) values ('Children of the Decree (Das Experiment 770 - Gebären auf Befehl)', 'Documentary', 2);
insert into subject (name, description, grade) values ('Latin Music USA', 'Documentary|Musical', 2);
insert into subject (name, description, grade) values ('Comedy, The', 'Drama', 4);
insert into subject (name, description, grade) values ('Great Dictator, The', 'Comedy|Drama|War', 2);
insert into subject (name, description, grade) values ('S.O.S. Coast Guard', 'Action|Adventure|Sci-Fi|Thriller', 2);
insert into subject (name, description, grade) values ('Temptation of St. Tony, The (Püha Tõnu kiusamine)', 'Drama|Fantasy|Mystery', 2);
insert into subject (name, description, grade) values ('Wes Craven''s New Nightmare (Nightmare on Elm Street Part 7: Freddy''s Finale, A)', 'Drama|Horror|Mystery|Thriller', 1);
insert into subject (name, description, grade) values ('Dangerous Davies: The Last Detective', 'Comedy|Crime', 2);
insert into subject (name, description, grade) values ('Frozen Fever', 'Adventure|Animation', 2);
insert into subject (name, description, grade) values ('Brunet Will Call (Brunet wieczorowa pora)', 'Comedy', 2);
insert into subject (name, description, grade) values ('Just Like a Woman', 'Drama', 1);
insert into subject (name, description, grade) values ('As You Like It', 'Comedy|Drama|Romance', 2);
insert into subject (name, description, grade) values ('While the City Sleeps', 'Drama|Film-Noir', 3);
insert into subject (name, description, grade) values ('Drunken Tai Chi (Siu taai gik)', 'Action|Comedy', 1);
insert into subject (name, description, grade) values ('Lille Fridolf and I', 'Comedy', 4);
insert into subject (name, description, grade) values ('Return Of The Ghostbusters', 'Comedy', 3);
insert into subject (name, description, grade) values ('Seeker: The Dark Is Rising, The', 'Action|Adventure|Drama|Fantasy', 4);
insert into subject (name, description, grade) values ('Champagne', 'Comedy', 2);
insert into subject (name, description, grade) values ('21', 'Crime|Drama|Romance|Thriller', 2);
insert into subject (name, description, grade) values ('Listen Up Philip', 'Drama', 1);
insert into subject (name, description, grade) values ('Mute Witness', 'Comedy|Horror|Thriller', 3);
insert into subject (name, description, grade) values ('Bring It On: In It To Win It', 'Comedy', 4);
insert into subject (name, description, grade) values ('Imagine', 'Drama', 4);
insert into subject (name, description, grade) values ('Nugget, The', 'Comedy', 3);
insert into subject (name, description, grade) values ('Little Man', 'Comedy', 1);
insert into subject (name, description, grade) values ('After School Midnighters (Hôkago middonaitâzu)', 'Action|Animation|Children|Comedy|Fantasy', 1);
insert into subject (name, description, grade) values ('Starfighters, The', 'Drama', 3);
insert into subject (name, description, grade) values ('Täynnä Tarmoa', 'Documentary', 2);
insert into subject (name, description, grade) values ('Violent City (Family, The) (Città violenta)', 'Action|Crime|Drama', 1);
insert into subject (name, description, grade) values ('Pink Floyd: The Wall', 'Drama|Musical', 1);
insert into subject (name, description, grade) values ('Tarzan Finds a Son!', 'Action|Adventure', 2);
insert into subject (name, description, grade) values ('Scream 4', 'Comedy|Horror|Mystery|Thriller', 4);
insert into subject (name, description, grade) values ('Wheel, The (La Roue)', 'Drama', 2);
insert into subject (name, description, grade) values ('Thanks for Sharing', 'Comedy|Drama', 1);
insert into subject (name, description, grade) values ('Antiviral', 'Horror|Sci-Fi|Thriller', 1);
insert into subject (name, description, grade) values ('Billy Jack Goes to Washington', 'Drama', 2);
insert into subject (name, description, grade) values ('My Bloody Valentine', 'Drama|Horror|Thriller', 1);
insert into subject (name, description, grade) values ('Match Factory Girl, The (Tulitikkutehtaan tyttö)', 'Comedy|Drama', 1);
insert into subject (name, description, grade) values ('Cat Chaser', 'Action|Thriller', 4);
insert into subject (name, description, grade) values ('Let Him Have It', 'Crime|Drama', 2);
insert into subject (name, description, grade) values ('Simon Magus', 'Drama|Fantasy|Mystery|Romance', 4);